---
title: "grafica3d"
author: "Sergio Nava"
date: "2023-03-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(plotly)
```

## Grafica en 3D

```{r}
x <- y <- seq(0,10,by=.5)
z <- 50 + outer(10 * x ,  7*y ,"+")

fig <- plot_ly(x=x, y=y, z = z)
fig <- fig %>% add_surface(
    contours = list(
    z = list(
      show=TRUE,
      usecolormap=TRUE,
      highlightcolor="#ff0000",
      project=list(z=TRUE)
      )
    )
)
fig

```

```{r}

mtcars$am[which(mtcars$am == 0)] <- 'Automatic'
mtcars$am[which(mtcars$am == 1)] <- 'Manual'
mtcars$am <- as.factor(mtcars$am)

fig <- plot_ly(mtcars, x = ~wt, y = ~hp, z = ~qsec, color = ~am, colors = c('#BF382A', '#0C4B8E'))
fig <- fig %>% add_markers()
fig <- fig %>% layout(scene = list(xaxis = list(title = 'Weight'),
                     yaxis = list(title = 'Gross horsepower'),
                     zaxis = list(title = '1/4 mile time')))
fig
```




```{r}
Datos <- data.frame(y=c(10,17,48,27,55,26,9,16),
                    x1=c(2,3,4,1,5,6,7,8),
                    x2=c(1,2,5,2,6,4,3,4))
plot(Datos)
fig <- plot_ly(Datos, x = ~x1, y = ~x2, z = ~y)
fig <- fig %>% add_markers()

fig
```

